version: '3.8'

services:
  gahiraios-dev:
    build: .
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    working_dir: /workspace
    tty: true
    stdin_open: true
    privileged: true  # Needed for QEMU KVM acceleration
    command: /bin/bash
